import { SupabaseClient } from '@supabase/supabase-js'
import {
  JobInvoice,
  JobInvoiceItem,
  InvoicePayment,
  InvoiceWithItems,
  InvoiceItemInput,
  InvoiceBalance,
  InvoiceStatus,
  InvoiceKind,
  DepositInfo,
} from './types/invoices'
import { enqueueInvoiceFinalized, enqueueInvoiceVoided } from './integrations'
import { formatCurrency } from './job-payments'

/**
 * Get all active (non-void) invoices for a job
 */
export async function getActiveInvoices(
  supabase: SupabaseClient,
  jobId: string
): Promise<JobInvoice[]> {
  const { data, error } = await supabase
    .from('job_invoices')
    .select('*')
    .eq('job_id', jobId)
    .neq('status', 'void')
    .order('created_at', { ascending: true })

  if (error) {
    throw new Error(`Failed to get invoices: ${error.message}`)
  }

  return (data || []) as JobInvoice[]
}

/**
 * Check if an active deposit invoice exists for a job
 */
export async function hasActiveDepositInvoice(
  supabase: SupabaseClient,
  jobId: string
): Promise<boolean> {
  const { data, error } = await supabase
    .from('job_invoices')
    .select('id')
    .eq('job_id', jobId)
    .eq('invoice_kind', 'deposit')
    .neq('status', 'void')
    .limit(1)

  if (error) {
    console.error('Error checking deposit invoice:', error)
    return false
  }

  return (data?.length || 0) > 0
}

/**
 * Get deposit information for a job including payments and invoice status
 */
export async function getDepositInfo(
  supabase: SupabaseClient,
  jobId: string
): Promise<DepositInfo> {
  // Get job sale amount and deposit percent
  const { data: job } = await supabase
    .from('production_jobs')
    .select('sale_amount, deposit_required_percent')
    .eq('id', jobId)
    .single()

  const saleAmountCents = Math.round((job?.sale_amount || 0) * 100)
  const depositPercent = job?.deposit_required_percent || 0.5
  const requiredDepositCents = Math.round(saleAmountCents * depositPercent)

  // Get all deposit payments
  const { data: payments } = await supabase
    .from('job_payments')
    .select('id, amount_cents')
    .eq('job_id', jobId)
    .eq('payment_type', 'deposit')

  const depositPayments = (payments || []).filter(p => p.amount_cents > 0)
  const totalDepositCents = depositPayments.reduce((sum, p) => sum + p.amount_cents, 0)

  // Check for active deposit invoice
  const { data: depositInvoices } = await supabase
    .from('job_invoices')
    .select('id, total_cents')
    .eq('job_id', jobId)
    .eq('invoice_kind', 'deposit')
    .neq('status', 'void')

  const hasActiveDepositInvoice = (depositInvoices?.length || 0) > 0

  // Get total applied to deposit invoices
  let appliedDepositCents = 0
  if (depositInvoices && depositInvoices.length > 0) {
    const invoiceIds = depositInvoices.map(i => i.id)
    const { data: appliedPayments } = await supabase
      .from('invoice_payments')
      .select('applied_cents')
      .in('invoice_id', invoiceIds)

    appliedDepositCents = (appliedPayments || []).reduce((sum, p) => sum + p.applied_cents, 0)
  }

  return {
    hasDeposit: depositPayments.length > 0,
    depositPayments,
    totalDepositCents,
    saleAmountCents,
    requiredDepositCents,
    hasActiveDepositInvoice,
    appliedDepositCents,
  }
}

/**
 * Create a new invoice for a job.
 * If defaultFromJobTotal is true, creates a single line item from job's sale_amount.
 */
export async function createInvoiceForJob(
  supabase: SupabaseClient,
  jobId: string,
  createdBy: string,
  defaultFromJobTotal: boolean = false
): Promise<JobInvoice> {
  // Create the invoice (invoice_number auto-generated by trigger)
  const { data: invoice, error: invoiceError } = await supabase
    .from('job_invoices')
    .insert({
      job_id: jobId,
      created_by: createdBy,
      status: 'draft',
    })
    .select()
    .single()

  if (invoiceError || !invoice) {
    throw new Error(`Failed to create invoice: ${invoiceError?.message || 'Unknown error'}`)
  }

  // If requested, add default line item from job total
  if (defaultFromJobTotal) {
    const { data: job } = await supabase
      .from('production_jobs')
      .select('sale_amount, job_type')
      .eq('id', jobId)
      .single()

    if (job?.sale_amount) {
      const saleAmountCents = Math.round(job.sale_amount * 100)
      await addInvoiceItem(supabase, invoice.id, {
        description: `${job.job_type || 'Roofing'} - Per Contract`,
        qty: 1,
        unit_price_cents: saleAmountCents,
      })

      // Refresh invoice to get updated totals
      const { data: refreshed } = await supabase
        .from('job_invoices')
        .select()
        .eq('id', invoice.id)
        .single()

      if (refreshed) return refreshed as JobInvoice
    }
  }

  return invoice as JobInvoice
}

/**
 * Sum of non-void invoice totals for a job (used for remaining-balance checks).
 */
export async function getTotalInvoicedCentsForJob(
  supabase: SupabaseClient,
  jobId: string
): Promise<number> {
  const { data: rows } = await supabase
    .from('job_invoices')
    .select('total_cents')
    .eq('job_id', jobId)
    .neq('status', 'void')

  return (rows || []).reduce((sum, r) => sum + (r.total_cents || 0), 0)
}

/**
 * Create a standard invoice with a single line at a custom amount (e.g. progress billing).
 * Amount cannot exceed remaining contract balance when the job has a positive sale amount.
 */
export async function createCustomAmountInvoice(
  supabase: SupabaseClient,
  jobId: string,
  createdBy: string,
  amountCents: number,
  lineDescription?: string | null
): Promise<JobInvoice> {
  if (!Number.isFinite(amountCents) || amountCents <= 0) {
    throw new Error('Amount must be greater than zero')
  }

  const { data: job } = await supabase
    .from('production_jobs')
    .select('sale_amount, job_type')
    .eq('id', jobId)
    .single()

  const saleAmountCents = Math.round((job?.sale_amount || 0) * 100)

  if (saleAmountCents > 0) {
    const totalInvoiced = await getTotalInvoicedCentsForJob(supabase, jobId)
    const remaining = saleAmountCents - totalInvoiced
    if (amountCents > remaining) {
      throw new Error(
        `Amount exceeds remaining contract balance (${formatCurrency(Math.max(0, remaining))} available of ${formatCurrency(saleAmountCents)} contract)`
      )
    }
  }

  const { data: invoice, error: invoiceError } = await supabase
    .from('job_invoices')
    .insert({
      job_id: jobId,
      created_by: createdBy,
      status: 'draft',
      invoice_kind: 'standard',
    })
    .select()
    .single()

  if (invoiceError || !invoice) {
    throw new Error(`Failed to create invoice: ${invoiceError?.message || 'Unknown error'}`)
  }

  const defaultDesc = `${job?.job_type || 'Roofing'} - Per Contract`
  const description = lineDescription?.trim() || defaultDesc

  await addInvoiceItem(supabase, invoice.id, {
    description,
    qty: 1,
    unit_price_cents: amountCents,
  })

  const { data: refreshed } = await supabase
    .from('job_invoices')
    .select()
    .eq('id', invoice.id)
    .single()

  return (refreshed || invoice) as JobInvoice
}

/**
 * Create a deposit invoice for a job.
 * - Checks for existing active deposit invoice (prevents duplicates)
 * - Creates invoice with deposit amount
 * - Adds single line item "Deposit (50%)"
 * - Auto-applies all deposit payments
 * - Sets status based on applied vs total
 */
export async function createDepositInvoiceV2(
  supabase: SupabaseClient,
  jobId: string,
  createdBy: string
): Promise<JobInvoice> {
  // Check for existing active deposit invoice
  const hasExisting = await hasActiveDepositInvoice(supabase, jobId)
  if (hasExisting) {
    throw new Error('An active deposit invoice already exists for this job')
  }

  // Get deposit info
  const depositInfo = await getDepositInfo(supabase, jobId)
  
  if (!depositInfo.hasDeposit) {
    throw new Error('No deposit payments found for this job')
  }

  // Use total deposit payments as invoice amount (or required deposit, whichever is less)
  const invoiceAmountCents = Math.min(
    depositInfo.totalDepositCents,
    depositInfo.requiredDepositCents
  )

  // Create the invoice with kind = 'deposit'
  const { data: invoice, error: invoiceError } = await supabase
    .from('job_invoices')
    .insert({
      job_id: jobId,
      created_by: createdBy,
      status: 'draft',
      invoice_kind: 'deposit',
      subtotal_cents: invoiceAmountCents,
      total_cents: invoiceAmountCents,
      issued_at: new Date().toISOString().split('T')[0],
      public_note: 'Remaining balance due at installation.',
    })
    .select()
    .single()

  if (invoiceError || !invoice) {
    throw new Error(`Failed to create invoice: ${invoiceError?.message || 'Unknown error'}`)
  }

  // Add deposit line item
  const depositPercent = Math.round((invoiceAmountCents / depositInfo.saleAmountCents) * 100)
  const { error: itemError } = await supabase
    .from('job_invoice_items')
    .insert({
      invoice_id: invoice.id,
      description: `Deposit (${depositPercent}%)`,
      qty: 1,
      unit_price_cents: invoiceAmountCents,
      line_total_cents: invoiceAmountCents,
      sort_order: 0,
    })

  if (itemError) {
    throw new Error(`Failed to add deposit item: ${itemError.message}`)
  }

  // Auto-apply all deposit payments
  let totalApplied = 0
  for (const payment of depositInfo.depositPayments) {
    const amountToApply = Math.min(payment.amount_cents, invoiceAmountCents - totalApplied)
    if (amountToApply <= 0) break

    const { error: paymentError } = await supabase
      .from('invoice_payments')
      .insert({
        invoice_id: invoice.id,
        job_payment_id: payment.id,
        applied_cents: amountToApply,
      })

    if (paymentError) {
      console.error('Failed to apply payment:', paymentError)
    } else {
      totalApplied += amountToApply
    }
  }

  // Determine status based on applied amount
  const newStatus: InvoiceStatus = totalApplied >= invoiceAmountCents 
    ? 'paid' 
    : totalApplied > 0 
      ? 'partially_paid' 
      : 'sent'

  // Update invoice status
  const { data: finalInvoice, error: finalError } = await supabase
    .from('job_invoices')
    .update({ status: newStatus })
    .eq('id', invoice.id)
    .select()
    .single()

  if (finalError || !finalInvoice) {
    throw new Error(`Failed to finalize invoice: ${finalError?.message || 'Unknown error'}`)
  }

  return finalInvoice as JobInvoice
}

/**
 * Create a final invoice for a job (remaining balance after deposit).
 * - total = sale_amount - applied_deposit_total
 * - Line item: "Remaining Balance"
 */
export async function createFinalInvoice(
  supabase: SupabaseClient,
  jobId: string,
  createdBy: string
): Promise<JobInvoice> {
  // Get deposit info to calculate remaining balance
  const depositInfo = await getDepositInfo(supabase, jobId)
  
  // Final invoice amount = sale amount - deposit already invoiced/applied
  const finalAmountCents = depositInfo.saleAmountCents - depositInfo.appliedDepositCents

  if (finalAmountCents <= 0) {
    throw new Error('No remaining balance to invoice')
  }

  // Create the invoice with kind = 'final'
  const { data: invoice, error: invoiceError } = await supabase
    .from('job_invoices')
    .insert({
      job_id: jobId,
      created_by: createdBy,
      status: 'draft',
      invoice_kind: 'final',
      subtotal_cents: finalAmountCents,
      total_cents: finalAmountCents,
      public_note: 'Payment due upon completion.',
    })
    .select()
    .single()

  if (invoiceError || !invoice) {
    throw new Error(`Failed to create invoice: ${invoiceError?.message || 'Unknown error'}`)
  }

  // Add line item for remaining balance
  const { error: itemError } = await supabase
    .from('job_invoice_items')
    .insert({
      invoice_id: invoice.id,
      description: 'Remaining Balance - Per Contract',
      qty: 1,
      unit_price_cents: finalAmountCents,
      line_total_cents: finalAmountCents,
      sort_order: 0,
    })

  if (itemError) {
    throw new Error(`Failed to add line item: ${itemError.message}`)
  }

  return invoice as JobInvoice
}

/**
 * Legacy function - kept for backwards compatibility
 * @deprecated Use createDepositInvoiceV2 instead
 */
export async function createDepositInvoice(
  supabase: SupabaseClient,
  jobId: string,
  createdBy: string,
  depositPaymentId: string,
  depositAmountCents: number
): Promise<JobInvoice> {
  // Check for existing active deposit invoice
  const hasExisting = await hasActiveDepositInvoice(supabase, jobId)
  if (hasExisting) {
    throw new Error('An active deposit invoice already exists for this job')
  }

  // Create the invoice with kind = 'deposit'
  const { data: invoice, error: invoiceError } = await supabase
    .from('job_invoices')
    .insert({
      job_id: jobId,
      created_by: createdBy,
      status: 'draft',
      invoice_kind: 'deposit',
      subtotal_cents: depositAmountCents,
      total_cents: depositAmountCents,
      issued_at: new Date().toISOString().split('T')[0],
    })
    .select()
    .single()

  if (invoiceError || !invoice) {
    throw new Error(`Failed to create invoice: ${invoiceError?.message || 'Unknown error'}`)
  }

  // Add deposit line item
  const { error: itemError } = await supabase
    .from('job_invoice_items')
    .insert({
      invoice_id: invoice.id,
      description: 'Deposit (50%)',
      qty: 1,
      unit_price_cents: depositAmountCents,
      line_total_cents: depositAmountCents,
      sort_order: 0,
    })

  if (itemError) {
    throw new Error(`Failed to add deposit item: ${itemError.message}`)
  }

  // Apply the deposit payment to this invoice
  const { error: paymentError } = await supabase
    .from('invoice_payments')
    .insert({
      invoice_id: invoice.id,
      job_payment_id: depositPaymentId,
      applied_cents: depositAmountCents,
    })

  if (paymentError) {
    throw new Error(`Failed to apply payment: ${paymentError.message}`)
  }

  // Mark invoice as paid (since deposit fully covers it)
  const { data: finalInvoice, error: finalError } = await supabase
    .from('job_invoices')
    .update({ status: 'paid' })
    .eq('id', invoice.id)
    .select()
    .single()

  if (finalError || !finalInvoice) {
    throw new Error(`Failed to finalize invoice: ${finalError?.message || 'Unknown error'}`)
  }

  return finalInvoice as JobInvoice
}

/**
 * Add a line item to a draft invoice.
 * Automatically recalculates invoice totals.
 */
export async function addInvoiceItem(
  supabase: SupabaseClient,
  invoiceId: string,
  item: InvoiceItemInput
): Promise<JobInvoiceItem> {
  // Verify invoice is draft
  const { data: invoice } = await supabase
    .from('job_invoices')
    .select('status')
    .eq('id', invoiceId)
    .single()

  if (!invoice) {
    throw new Error('Invoice not found')
  }

  if (invoice.status !== 'draft') {
    throw new Error('Cannot add items to non-draft invoice. Create a new invoice instead.')
  }

  const qty = item.qty ?? 1
  const lineTotalCents = Math.round(qty * item.unit_price_cents)

  // Get current max sort_order
  const { data: maxOrder } = await supabase
    .from('job_invoice_items')
    .select('sort_order')
    .eq('invoice_id', invoiceId)
    .order('sort_order', { ascending: false })
    .limit(1)
    .single()

  const sortOrder = item.sort_order ?? ((maxOrder?.sort_order ?? -1) + 1)

  const { data: newItem, error } = await supabase
    .from('job_invoice_items')
    .insert({
      invoice_id: invoiceId,
      description: item.description,
      qty,
      unit_price_cents: item.unit_price_cents,
      line_total_cents: lineTotalCents,
      sort_order: sortOrder,
    })
    .select()
    .single()

  if (error || !newItem) {
    throw new Error(`Failed to add invoice item: ${error?.message || 'Unknown error'}`)
  }

  // Recalculate invoice totals
  await recalculateInvoiceTotals(supabase, invoiceId)

  return newItem as JobInvoiceItem
}

/**
 * Update a line item on a draft invoice.
 */
export async function updateInvoiceItem(
  supabase: SupabaseClient,
  itemId: string,
  updates: Partial<InvoiceItemInput>
): Promise<JobInvoiceItem> {
  // Get current item
  const { data: currentItem } = await supabase
    .from('job_invoice_items')
    .select('*, job_invoices!inner(status)')
    .eq('id', itemId)
    .single()

  if (!currentItem) {
    throw new Error('Invoice item not found')
  }

  if ((currentItem as any).job_invoices?.status !== 'draft') {
    throw new Error('Cannot update items on non-draft invoice')
  }

  const qty = updates.qty ?? currentItem.qty
  const unitPriceCents = updates.unit_price_cents ?? currentItem.unit_price_cents
  const lineTotalCents = Math.round(qty * unitPriceCents)

  const { data: updated, error } = await supabase
    .from('job_invoice_items')
    .update({
      description: updates.description ?? currentItem.description,
      qty,
      unit_price_cents: unitPriceCents,
      line_total_cents: lineTotalCents,
      sort_order: updates.sort_order ?? currentItem.sort_order,
    })
    .eq('id', itemId)
    .select()
    .single()

  if (error || !updated) {
    throw new Error(`Failed to update invoice item: ${error?.message || 'Unknown error'}`)
  }

  // Recalculate invoice totals
  await recalculateInvoiceTotals(supabase, currentItem.invoice_id)

  return updated as JobInvoiceItem
}

/**
 * Delete a line item from a draft invoice.
 */
export async function deleteInvoiceItem(
  supabase: SupabaseClient,
  itemId: string
): Promise<void> {
  const { data: item } = await supabase
    .from('job_invoice_items')
    .select('invoice_id, job_invoices!inner(status)')
    .eq('id', itemId)
    .single()

  if (!item) {
    throw new Error('Invoice item not found')
  }

  if ((item as any).job_invoices?.status !== 'draft') {
    throw new Error('Cannot delete items from non-draft invoice')
  }

  const { error } = await supabase
    .from('job_invoice_items')
    .delete()
    .eq('id', itemId)

  if (error) {
    throw new Error(`Failed to delete invoice item: ${error.message}`)
  }

  await recalculateInvoiceTotals(supabase, item.invoice_id)
}

/**
 * Recalculate invoice subtotal and total from line items.
 */
async function recalculateInvoiceTotals(
  supabase: SupabaseClient,
  invoiceId: string
): Promise<void> {
  const { data: items } = await supabase
    .from('job_invoice_items')
    .select('line_total_cents')
    .eq('invoice_id', invoiceId)

  const subtotalCents = (items || []).reduce((sum, item) => sum + item.line_total_cents, 0)
  const totalCents = subtotalCents // No tax for now, can add later

  await supabase
    .from('job_invoices')
    .update({
      subtotal_cents: subtotalCents,
      total_cents: totalCents,
    })
    .eq('id', invoiceId)
}

/**
 * Finalize and send an invoice.
 * Sets status to 'sent', records sent_at and email.
 * PDF generation is handled separately via the /api/invoices/[id]/pdf endpoint.
 * Email sending is stubbed - integrate with your email service.
 */
export async function finalizeAndSendInvoice(
  supabase: SupabaseClient,
  invoiceId: string,
  email: string,
  generatePdf: boolean = true
): Promise<JobInvoice> {
  // Verify invoice exists and is draft
  const { data: invoice } = await supabase
    .from('job_invoices')
    .select('*, job_invoice_items(*)')
    .eq('id', invoiceId)
    .single()

  if (!invoice) {
    throw new Error('Invoice not found')
  }

  if (invoice.status !== 'draft') {
    throw new Error('Only draft invoices can be sent')
  }

  if (!invoice.job_invoice_items || invoice.job_invoice_items.length === 0) {
    throw new Error('Cannot send invoice with no line items')
  }

  if (invoice.total_cents <= 0) {
    throw new Error('Cannot send invoice with zero total')
  }

  const now = new Date().toISOString()
  const today = now.split('T')[0]

  const { data: updated, error } = await supabase
    .from('job_invoices')
    .update({
      status: 'sent',
      issued_at: today,
      due_at: invoice.due_at || today,
      sent_at: now,
      sent_to_email: email,
    })
    .eq('id', invoiceId)
    .select()
    .single()

  if (error || !updated) {
    throw new Error(`Failed to send invoice: ${error?.message || 'Unknown error'}`)
  }

  // Get job info for integration event
  const { data: job } = await supabase
    .from('production_jobs')
    .select('org_id, customer_id')
    .eq('id', invoice.job_id)
    .single()

  // Get line items for integration payload
  const { data: items } = await supabase
    .from('job_invoice_items')
    .select('description, qty, unit_price_cents, line_total_cents')
    .eq('invoice_id', invoiceId)

  // Enqueue integration event
  if (job) {
    enqueueInvoiceFinalized(supabase, job.org_id, invoiceId, {
      invoice_number: updated.invoice_number,
      customer_id: job.customer_id,
      total_cents: updated.total_cents,
      issued_at: today,
      due_at: updated.due_at,
      line_items: items || [],
    }).catch(err => console.error('Failed to enqueue invoice event:', err))
  }

  // TODO: Integrate with email service to actually send the invoice
  console.log(`[STUB] Invoice ${updated.invoice_number} sent to ${email}`)

  return updated as JobInvoice
}

/**
 * Apply a job payment to an invoice.
 * Automatically updates invoice status based on payment coverage.
 */
export async function applyPaymentToInvoice(
  supabase: SupabaseClient,
  invoiceId: string,
  jobPaymentId: string,
  appliedCents: number,
  createdBy?: string
): Promise<InvoicePayment> {
  if (appliedCents <= 0) {
    throw new Error('Applied amount must be positive')
  }

  // Verify invoice exists and is not void/draft
  const { data: invoice } = await supabase
    .from('job_invoices')
    .select('status, total_cents')
    .eq('id', invoiceId)
    .single()

  if (!invoice) {
    throw new Error('Invoice not found')
  }

  if (invoice.status === 'void') {
    throw new Error('Cannot apply payment to voided invoice')
  }

  if (invoice.status === 'draft') {
    throw new Error('Cannot apply payment to draft invoice. Send it first.')
  }

  // Verify payment exists and belongs to same job
  const { data: payment } = await supabase
    .from('job_payments')
    .select('id, amount_cents, job_id')
    .eq('id', jobPaymentId)
    .single()

  if (!payment) {
    throw new Error('Payment not found')
  }

  // Check payment isn't already fully applied
  const { data: existingApplications } = await supabase
    .from('invoice_payments')
    .select('applied_cents')
    .eq('job_payment_id', jobPaymentId)

  const totalApplied = (existingApplications || []).reduce((sum, a) => sum + a.applied_cents, 0)
  const remainingPayment = payment.amount_cents - totalApplied

  if (appliedCents > remainingPayment) {
    throw new Error(`Cannot apply ${appliedCents} cents. Only ${remainingPayment} cents remaining from this payment.`)
  }

  // Create the application
  const { data: application, error } = await supabase
    .from('invoice_payments')
    .insert({
      invoice_id: invoiceId,
      job_payment_id: jobPaymentId,
      applied_cents: appliedCents,
      created_by: createdBy,
    })
    .select()
    .single()

  if (error || !application) {
    throw new Error(`Failed to apply payment: ${error?.message || 'Unknown error'}`)
  }

  // Update invoice status based on total applied
  await updateInvoicePaymentStatus(supabase, invoiceId)

  return application as InvoicePayment
}

/**
 * Update invoice status based on applied payments.
 */
async function updateInvoicePaymentStatus(
  supabase: SupabaseClient,
  invoiceId: string
): Promise<void> {
  const balance = await computeInvoiceBalance(supabase, invoiceId)

  let newStatus: InvoiceStatus
  if (balance.is_paid) {
    newStatus = 'paid'
  } else if (balance.applied_cents > 0) {
    newStatus = 'partially_paid'
  } else {
    newStatus = 'sent' // Keep as sent if no payments
  }

  // Only update if status would change (and not void)
  const { data: current } = await supabase
    .from('job_invoices')
    .select('status')
    .eq('id', invoiceId)
    .single()

  if (current && current.status !== 'void' && current.status !== newStatus) {
    await supabase
      .from('job_invoices')
      .update({ status: newStatus })
      .eq('id', invoiceId)
  }
}

/**
 * Compute the balance for an invoice.
 */
export async function computeInvoiceBalance(
  supabase: SupabaseClient,
  invoiceId: string
): Promise<InvoiceBalance> {
  const { data: invoice } = await supabase
    .from('job_invoices')
    .select('total_cents')
    .eq('id', invoiceId)
    .single()

  if (!invoice) {
    throw new Error('Invoice not found')
  }

  const { data: applications } = await supabase
    .from('invoice_payments')
    .select('applied_cents')
    .eq('invoice_id', invoiceId)

  const appliedCents = (applications || []).reduce((sum, a) => sum + a.applied_cents, 0)
  const balanceCents = invoice.total_cents - appliedCents

  return {
    total_cents: invoice.total_cents,
    applied_cents: appliedCents,
    balance_cents: balanceCents,
    is_paid: balanceCents <= 0,
  }
}

/**
 * Get invoice with all items and payments.
 */
export async function getInvoiceWithDetails(
  supabase: SupabaseClient,
  invoiceId: string
): Promise<InvoiceWithItems | null> {
  const { data: invoice } = await supabase
    .from('job_invoices')
    .select('*')
    .eq('id', invoiceId)
    .single()

  if (!invoice) return null

  const { data: items } = await supabase
    .from('job_invoice_items')
    .select('*')
    .eq('invoice_id', invoiceId)
    .order('sort_order', { ascending: true })

  const { data: payments } = await supabase
    .from('invoice_payments')
    .select('*')
    .eq('invoice_id', invoiceId)
    .order('created_at', { ascending: true })

  const appliedCents = (payments || []).reduce((sum, p) => sum + p.applied_cents, 0)

  return {
    ...invoice,
    items: items || [],
    payments: payments || [],
    applied_cents: appliedCents,
    balance_cents: invoice.total_cents - appliedCents,
  } as InvoiceWithItems
}

/**
 * Get all invoices for a job.
 */
export async function getInvoicesForJob(
  supabase: SupabaseClient,
  jobId: string
): Promise<JobInvoice[]> {
  const { data, error } = await supabase
    .from('job_invoices')
    .select('*')
    .eq('job_id', jobId)
    .order('created_at', { ascending: false })

  if (error) {
    throw new Error(`Failed to fetch invoices: ${error.message}`)
  }

  return (data || []) as JobInvoice[]
}

/**
 * Void an invoice.
 */
export async function voidInvoice(
  supabase: SupabaseClient,
  invoiceId: string,
  reason: string
): Promise<JobInvoice> {
  if (!reason.trim()) {
    throw new Error('Void reason is required')
  }

  const { data: invoice } = await supabase
    .from('job_invoices')
    .select('status')
    .eq('id', invoiceId)
    .single()

  if (!invoice) {
    throw new Error('Invoice not found')
  }

  if (invoice.status === 'void') {
    throw new Error('Invoice is already voided')
  }

  if (invoice.status === 'paid') {
    throw new Error('Cannot void a paid invoice. Refund payments first.')
  }

  const { data: updated, error } = await supabase
    .from('job_invoices')
    .update({
      status: 'void',
      voided_at: new Date().toISOString(),
      void_reason: reason.trim(),
    })
    .eq('id', invoiceId)
    .select('*, production_jobs!inner(org_id)')
    .single()

  if (error || !updated) {
    throw new Error(`Failed to void invoice: ${error?.message || 'Unknown error'}`)
  }

  // Enqueue integration event
  const orgId = (updated as any).production_jobs?.org_id
  if (orgId) {
    enqueueInvoiceVoided(
      supabase,
      orgId,
      invoiceId,
      updated.invoice_number,
      reason.trim()
    ).catch(err => console.error('Failed to enqueue void event:', err))
  }

  return updated as JobInvoice
}

/**
 * Duplicate an invoice as a new draft.
 * Useful when needing to revise a sent invoice.
 */
export async function duplicateInvoiceAsDraft(
  supabase: SupabaseClient,
  invoiceId: string,
  createdBy: string
): Promise<JobInvoice> {
  const original = await getInvoiceWithDetails(supabase, invoiceId)
  if (!original) {
    throw new Error('Invoice not found')
  }

  // Create new invoice
  const { data: newInvoice, error: invoiceError } = await supabase
    .from('job_invoices')
    .insert({
      job_id: original.job_id,
      created_by: createdBy,
      status: 'draft',
      notes: original.notes,
      public_note: original.public_note,
      internal_note: original.internal_note,
      due_at: original.due_at,
    })
    .select()
    .single()

  if (invoiceError || !newInvoice) {
    throw new Error(`Failed to duplicate invoice: ${invoiceError?.message || 'Unknown error'}`)
  }

  // Copy line items
  for (const item of original.items) {
    await addInvoiceItem(supabase, newInvoice.id, {
      description: item.description,
      qty: item.qty,
      unit_price_cents: item.unit_price_cents,
      sort_order: item.sort_order,
    })
  }

  // Refresh to get updated totals
  const { data: refreshed } = await supabase
    .from('job_invoices')
    .select()
    .eq('id', newInvoice.id)
    .single()

  return (refreshed || newInvoice) as JobInvoice
}

/**
 * Format cents as currency string.
 */
export function formatInvoiceCurrency(cents: number): string {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
  }).format(cents / 100)
}
