/** Static AHJ and external-source research for the coverage-gap report. */

export const JURISDICTION_ROWS: Array<Record<string, string>> = [
  {
    county: 'Cabarrus',
    municipality: 'Unincorporated Cabarrus',
    permitting_authority: 'Cabarrus County Construction Standards',
    county_or_city: 'county',
    historical_years: 'GIS yearly permits 2007–2015; Historical_2016–2018; Accela 2019–present',
    public_search: 'yes-accela',
    bulk_source: 'ArcGIS yearly + Historical_2016–2018 Permits; none after 2018',
    api: 'ArcGIS REST through 2018; no Accela bulk API found',
    solar_identifiable: 'yes-through-2018',
    address_available: 'yes',
    parcel_available: 'yes-PIN14',
    contractor_available: 'yes-AppName',
    currently_in_existing_extract: 'partial-through-2015-only',
    potential_gap: 'yes-2016-onward-not-in-extract; 2019-onward-no-bulk',
    notes:
      'County issues building/electrical for the whole county including cities. 2016–2018 layers exist but were not in the 7,312 extract. 2019+ permit GIS layers were not published.',
    source_url: 'https://www.cabarruscounty.us/Government/Departments/Construction-Standards',
  },
  {
    county: 'Cabarrus',
    municipality: 'Concord',
    permitting_authority: 'Cabarrus County Construction Standards (building); City zoning via same Accela',
    county_or_city: 'county',
    historical_years: 'Same as county Accela / GIS',
    public_search: 'yes-accela',
    bulk_source: 'Same county GIS; no separate city permit FeatureServer',
    api: 'none-beyond-county-GIS',
    solar_identifiable: 'yes-in-county-layers',
    address_available: 'yes',
    parcel_available: 'yes',
    contractor_available: 'yes-through-2018-GIS',
    currently_in_existing_extract: 'partial-through-2015',
    potential_gap: 'no-separate-city-AHJ; yes-missing-years-in-county-GIS',
    notes: 'Concord does not issue its own building/electrical permits. Gap is county GIS cutoff, not a city split.',
    source_url: 'https://concordnc.gov/Departments/Planning-Development-Services/Permits',
  },
  {
    county: 'Cabarrus',
    municipality: 'Kannapolis (Cabarrus portion)',
    permitting_authority: 'Cabarrus County Construction Standards',
    county_or_city: 'county',
    historical_years: 'Same as county',
    public_search: 'yes-accela',
    bulk_source: 'County GIS',
    api: 'none-beyond-county-GIS',
    solar_identifiable: 'yes-in-county-layers',
    address_available: 'yes',
    parcel_available: 'yes',
    contractor_available: 'yes-through-2018-GIS',
    currently_in_existing_extract: 'partial-through-2015',
    potential_gap: 'no-separate-city-building-AHJ; Rowan-side city limits still Cabarrus Accela; ETJ is Rowan',
    notes: 'Kannapolis city limits (including parcels in Rowan County) permit through Cabarrus Accela. Cabarrus Crystal report “Building Permits Rowan County” is that slice (date-range PIN/owner/address from Cabarrus systems). Rowan GIS L6 covers Kannapolis ETJ, not city-limit rows.',
    source_url: 'https://gis-cabarrus.opendata.arcgis.com/pages/building-reports',
  },
  {
    county: 'Cabarrus',
    municipality: 'Harrisburg',
    permitting_authority: 'Town zoning; Cabarrus County building/electrical',
    county_or_city: 'county',
    historical_years: 'Same as county',
    public_search: 'yes-accela',
    bulk_source: 'County GIS',
    api: 'none',
    solar_identifiable: 'yes-in-county-layers',
    address_available: 'yes',
    parcel_available: 'yes',
    contractor_available: 'yes-through-2018-GIS',
    currently_in_existing_extract: 'partial-through-2015',
    potential_gap: 'no-separate-city-building-AHJ',
    notes: 'Harrisburg zoning clearance then county building permit. Solar electrical is county.',
    source_url: 'https://www.harrisburgnc.gov/271/Permits',
  },
  {
    county: 'Mecklenburg',
    municipality: 'Charlotte',
    permitting_authority: 'Mecklenburg County Code Enforcement (LUESA)',
    county_or_city: 'county',
    historical_years: 'BuildingPermits ~1997–2023; EPIC Accela SolarPV 2024–present',
    public_search: 'yes-accela',
    bulk_source: 'meckgis BuildingPermits + EPIC_Accela SolarPV',
    api: 'ArcGIS REST',
    solar_identifiable: 'partial-legacy-SOLAR-keyword; yes-EPIC-SolarPV',
    address_available: 'yes',
    parcel_available: 'yes',
    contractor_available: 'no',
    currently_in_existing_extract: 'yes',
    potential_gap: 'no-city-building-AHJ; quality-gap-not-jurisdiction-gap',
    notes:
      'Charlotte does not issue building/electrical permits. City Accela is zoning/UDO/stormwater. Missing installer names, not missing city permits.',
    source_url: 'https://code.mecknc.gov/customer-tools/aca',
  },
  {
    county: 'Mecklenburg',
    municipality: 'Huntersville',
    permitting_authority: 'Mecklenburg County Code Enforcement; town zoning',
    county_or_city: 'county',
    historical_years: 'Same county feeds',
    public_search: 'yes-accela',
    bulk_source: 'Same county GIS',
    api: 'ArcGIS REST',
    solar_identifiable: 'same-as-county',
    address_available: 'yes',
    parcel_available: 'yes',
    contractor_available: 'no',
    currently_in_existing_extract: 'yes-if-in-county-layers',
    potential_gap: 'no',
    notes: 'Town zoning review; county issues the construction permit.',
    source_url: 'https://www.huntersville.org/2620/Land-Development',
  },
  {
    county: 'Mecklenburg',
    municipality: 'Cornelius',
    permitting_authority: 'Mecklenburg County Code Enforcement; town zoning',
    county_or_city: 'county',
    historical_years: 'Same county feeds',
    public_search: 'yes-accela',
    bulk_source: 'Same county GIS',
    api: 'ArcGIS REST',
    solar_identifiable: 'same-as-county',
    address_available: 'yes',
    parcel_available: 'yes',
    contractor_available: 'no',
    currently_in_existing_extract: 'yes-if-in-county-layers',
    potential_gap: 'no',
    notes: 'Building permits submitted through Mecklenburg County; town is auto-notified for zoning.',
    source_url: 'https://www.cornelius.org/government/departments/planning_/permits,_applications,___fees.php',
  },
  {
    county: 'Mecklenburg',
    municipality: 'Davidson',
    permitting_authority: 'Mecklenburg County Code Enforcement; town zoning',
    county_or_city: 'county',
    historical_years: 'Same county feeds',
    public_search: 'yes-accela',
    bulk_source: 'Same county GIS',
    api: 'ArcGIS REST',
    solar_identifiable: 'same-as-county',
    address_available: 'yes',
    parcel_available: 'yes',
    contractor_available: 'no',
    currently_in_existing_extract: 'yes-if-in-county-layers',
    potential_gap: 'no',
    notes: 'Same Mecklenburg county-AHJ pattern as other north-towns.',
    source_url: 'https://aca-prod.accela.com/MECKLENBURG',
  },
  {
    county: 'Mecklenburg',
    municipality: 'Matthews',
    permitting_authority: 'Mecklenburg County Code Enforcement; town zoning',
    county_or_city: 'county',
    historical_years: 'Same county feeds',
    public_search: 'yes-accela',
    bulk_source: 'Same county GIS',
    api: 'ArcGIS REST',
    solar_identifiable: 'same-as-county',
    address_available: 'yes',
    parcel_available: 'yes',
    contractor_available: 'no',
    currently_in_existing_extract: 'yes-if-in-county-layers',
    potential_gap: 'no',
    notes: 'County building/electrical AHJ.',
    source_url: 'https://aca-prod.accela.com/MECKLENBURG',
  },
  {
    county: 'Mecklenburg',
    municipality: 'Mint Hill',
    permitting_authority: 'Mecklenburg County Code Enforcement; town zoning',
    county_or_city: 'county',
    historical_years: 'Same county feeds',
    public_search: 'yes-accela',
    bulk_source: 'Same county GIS',
    api: 'ArcGIS REST',
    solar_identifiable: 'same-as-county',
    address_available: 'yes',
    parcel_available: 'yes',
    contractor_available: 'no',
    currently_in_existing_extract: 'yes-if-in-county-layers',
    potential_gap: 'no',
    notes: 'County building/electrical AHJ.',
    source_url: 'https://aca-prod.accela.com/MECKLENBURG',
  },
  {
    county: 'Mecklenburg',
    municipality: 'Pineville',
    permitting_authority: 'Mecklenburg County Code Enforcement; town zoning',
    county_or_city: 'county',
    historical_years: 'Same county feeds',
    public_search: 'yes-accela',
    bulk_source: 'Same county GIS',
    api: 'ArcGIS REST',
    solar_identifiable: 'same-as-county',
    address_available: 'yes',
    parcel_available: 'yes',
    contractor_available: 'no',
    currently_in_existing_extract: 'yes-if-in-county-layers',
    potential_gap: 'no',
    notes: 'County building/electrical AHJ.',
    source_url: 'https://aca-prod.accela.com/MECKLENBURG',
  },
  {
    county: 'Rowan',
    municipality: 'Unincorporated Rowan + listed towns',
    permitting_authority: 'Rowan County Building Inspections',
    county_or_city: 'county',
    historical_years: 'GIS Solar PV ~2014–2026',
    public_search: 'yes-energov-login-gated',
    bulk_source: 'ArcGIS Building_Permits MapServer/6',
    api: 'ArcGIS REST',
    solar_identifiable: 'yes-workclass',
    address_available: 'yes',
    parcel_available: 'yes-map-lot',
    contractor_available: 'partial',
    currently_in_existing_extract: 'yes',
    potential_gap: 'low-for-county-issued-permits',
    notes:
      'County covers Cleveland, China Grove, East Spencer, Faith, Granite Quarry, Kannapolis ETJ, Landis, Rockwell, Salisbury, Spencer.',
    source_url: 'https://www.rowancountync.gov/373/Building-Inspections',
  },
  {
    county: 'Rowan',
    municipality: 'Salisbury',
    permitting_authority: 'City zoning; Rowan County building/electrical',
    county_or_city: 'county',
    historical_years: 'Same county GIS',
    public_search: 'yes-county-css',
    bulk_source: 'County MapServer/6',
    api: 'ArcGIS REST',
    solar_identifiable: 'yes',
    address_available: 'yes',
    parcel_available: 'yes',
    contractor_available: 'partial',
    currently_in_existing_extract: 'yes',
    potential_gap: 'no-separate-city-building-AHJ',
    notes: 'City zoning permit then Rowan County building permit.',
    source_url: 'https://salisburync.gov/Business/Permits-and-Zoning',
  },
  {
    county: 'Union',
    municipality: 'Unincorporated Union + Indian Trail and most towns',
    permitting_authority: 'Union County Building Code Enforcement',
    county_or_city: 'county',
    historical_years: 'unknown-electronic-retention',
    public_search: 'yes-evolve',
    bulk_source: 'none-found',
    api: 'none',
    solar_identifiable: 'unknown',
    address_available: 'unknown',
    parcel_available: 'unknown',
    contractor_available: 'unknown',
    currently_in_existing_extract: 'no',
    potential_gap: 'yes-entire-county-not-extracted',
    notes: 'County issues building permits everywhere except Monroe and Waxhaw. Evolve search only. PRA.',
    source_url: 'https://www.unioncountync.gov/business/development-services',
  },
  {
    county: 'Union',
    municipality: 'Monroe',
    permitting_authority: 'City of Monroe Building Standards',
    county_or_city: 'city',
    historical_years: 'unknown',
    public_search: 'yes-cityview',
    bulk_source: 'none-found',
    api: 'none',
    solar_identifiable: 'unknown',
    address_available: 'unknown',
    parcel_available: 'unknown',
    contractor_available: 'unknown',
    currently_in_existing_extract: 'no',
    potential_gap: 'yes-separate-city-AHJ',
    notes: 'True municipal building AHJ. County extract would miss Monroe solar permits. CityView portal. Do not scrape.',
    source_url: 'https://nc-monroe.civicplus.com/204/Building-Standards',
  },
  {
    county: 'Union',
    municipality: 'Waxhaw',
    permitting_authority: 'Town of Waxhaw Building Inspections',
    county_or_city: 'city',
    historical_years: 'unknown',
    public_search: 'yes-permit-portal',
    bulk_source: 'none-found',
    api: 'none',
    solar_identifiable: 'unknown',
    address_available: 'unknown',
    parcel_available: 'unknown',
    contractor_available: 'unknown',
    currently_in_existing_extract: 'no',
    potential_gap: 'yes-separate-city-AHJ',
    notes: 'True municipal building AHJ. Union County authority excludes Waxhaw. Tyler EnerGov search was 503 when probed; PRA, do not scrape.',
    source_url: 'https://waxhawnc-energovpub.tylerhost.net/apps/citizenaccess/Site/Permit/Search',
  },
  {
    county: 'Union',
    municipality: 'Indian Trail',
    permitting_authority: 'Town zoning; Union County building/electrical',
    county_or_city: 'county',
    historical_years: 'unknown',
    public_search: 'yes-evolve-town-zoning',
    bulk_source: 'none-found',
    api: 'none',
    solar_identifiable: 'unknown',
    address_available: 'unknown',
    parcel_available: 'unknown',
    contractor_available: 'unknown',
    currently_in_existing_extract: 'no',
    potential_gap: 'yes-county-not-extracted; no-separate-building-AHJ',
    notes: 'Town zoning then Union County building permit. Not a second electrical AHJ.',
    source_url: 'https://www.indiantrail.org/DocumentCenter/View/261/Residential-Accessory-Structures-and-Additions',
  },
  {
    county: 'Gaston',
    municipality: 'Unincorporated Gaston + Belmont + Mount Holly',
    permitting_authority: 'Gaston County Building & Development Services',
    county_or_city: 'county',
    historical_years: 'unknown; EnerGov GIS token-gated',
    public_search: 'yes-energov',
    bulk_source: 'none-public (GIS 499 Token Required)',
    api: 'none-public',
    solar_identifiable: 'unknown',
    address_available: 'unknown',
    parcel_available: 'unknown',
    contractor_available: 'unknown',
    currently_in_existing_extract: 'no',
    potential_gap: 'yes-entire-county-not-extracted',
    notes: 'Belmont and Mount Holly: city zoning, county building. PRA. Do not scrape EnerGov.',
    source_url: 'https://selfservice.gastongov.com/energov_prod/selfservice#/home',
  },
  {
    county: 'Gaston',
    municipality: 'Gastonia',
    permitting_authority: 'City zoning (CityView); Gaston County construction permits since 2022-08-29',
    county_or_city: 'mixed',
    historical_years: 'City issued construction permits before 2022-08-29; county after',
    public_search: 'yes-cityview-and-county-energov',
    bulk_source: 'none-found',
    api: 'none',
    solar_identifiable: 'unknown',
    address_available: 'unknown',
    parcel_available: 'unknown',
    contractor_available: 'unknown',
    currently_in_existing_extract: 'no',
    potential_gap: 'yes-pre-2022-city-construction-permits-plus-county-not-extracted',
    notes:
      'After 29 Aug 2022 Gastonia issues zoning only; Gaston County issues construction permits. Historical city building permits are a real split.',
    source_url: 'https://www.cityofgastonia.com/doing-business/permits-inspections.html',
  },
  {
    county: 'Iredell',
    municipality: 'Unincorporated Iredell + Statesville',
    permitting_authority: 'Iredell County Building Standards',
    county_or_city: 'county',
    historical_years: 'unknown; EnerGov CSS',
    public_search: 'yes-energov',
    bulk_source: 'none-usable (History layer ~14 points)',
    api: 'none',
    solar_identifiable: 'unknown',
    address_available: 'unknown',
    parcel_available: 'unknown',
    contractor_available: 'unknown',
    currently_in_existing_extract: 'no',
    potential_gap: 'yes-entire-county-not-extracted',
    notes: 'Statesville zoning via county CSS partnership; county issues building permits. PRA.',
    source_url: 'https://iredellcountync.gov/234/Building-Standards-Division',
  },
  {
    county: 'Iredell',
    municipality: 'Mooresville',
    permitting_authority: 'Town of Mooresville Building Permitting & Inspections (created 2023); county before that',
    county_or_city: 'city-since-2023',
    historical_years: 'County until 2023; GeoCivix/town portal after',
    public_search: 'yes-town-portal',
    bulk_source: 'none-found',
    api: 'none',
    solar_identifiable: 'unknown',
    address_available: 'unknown',
    parcel_available: 'unknown',
    contractor_available: 'unknown',
    currently_in_existing_extract: 'no',
    potential_gap: 'yes-separate-city-AHJ-since-2023-plus-county-history-not-extracted',
    notes: 'True municipal building AHJ starting 2023. Pre-2023 Mooresville solar should be in Iredell County records.',
    source_url: 'https://mooresvillenc.gov/government/departments/building_permitting___inspections/index.php',
  },
  {
    county: 'Lincoln',
    municipality: 'Lincoln County (all)',
    permitting_authority: 'Lincoln County (eTRAKiT)',
    county_or_city: 'county',
    historical_years: 'unknown',
    public_search: 'yes-etrakit',
    bulk_source: 'none (TRAKiT GIS is parcels/addresses)',
    api: 'none',
    solar_identifiable: 'unknown',
    address_available: 'unknown',
    parcel_available: 'unknown',
    contractor_available: 'unknown',
    currently_in_existing_extract: 'no',
    potential_gap: 'yes-entire-county-not-extracted',
    notes: 'No municipal building-AHJ split found. PRA.',
    source_url: 'https://linc.csqrcloud.com/community-etrakit/',
  },
]

export const EXTERNAL_SOURCES: Array<Record<string, string>> = [
  {
    name: 'Duke Energy Carolinas Non-TOUD Net Metering Demand Report (NCUC E-7 Sub 1113)',
    url: 'http://ncrets.org/wp-content/uploads/sites/7/2024/01/DEC-NC-Non-TOUD-NM-Demand-Report-12-2023.pdf',
    access_method: 'public PDF in NCUC docket / NC REPS site',
    geography: 'DEC NC service territory; city + customer name + kW DC; no street address',
    has_address: 'no',
    has_parcel: 'no',
    has_zip: 'no',
    has_county: 'no',
    has_date: 'no-snapshot-through-2023-12-31',
    has_installer: 'no',
    has_capacity: 'yes-kW-DC',
    residential_focus: 'mostly-residential-net-metering',
    usable_for_volume: 'yes-best-independent-volume-check',
    notes:
      '20,299 customers statewide in DEC NC Non-TOUD NM through 2023-12-31. City hits: Charlotte 4,241; Concord 398; Kannapolis 218; Harrisburg 167; Salisbury 368; Matthews 187; Mooresville 427. Excludes TOU NM and DEP. Not a street-level canvass file.',
  },
  {
    name: 'Duke Energy Progress Non-TOUD Net Metering Demand Report (NCUC E-2 Sub 1106)',
    url: 'https://ncrets.org/wp-content/uploads/sites/7/2022/03/DEP-NC-Non-TOUD-NM-Demand-Report-02-2022.pdf',
    access_method: 'public PDF',
    geography: 'DEP NC; name + city + kW; older 2022 snapshot',
    has_address: 'no',
    has_parcel: 'no',
    has_zip: 'no',
    has_county: 'no',
    has_date: 'no',
    has_installer: 'no',
    has_capacity: 'yes',
    residential_focus: 'mostly-residential',
    usable_for_volume: 'limited-for-Charlotte-metro-DEC-territory',
    notes: 'Charlotte metro is overwhelmingly DEC, not DEP. Useful for eastern NC; weak for Meck/Cabarrus.',
  },
  {
    name: 'EIA Form 861 Net Metering',
    url: 'https://www.eia.gov/electricity/data/eia861/',
    access_method: 'annual CSV/XLS download, no scraping',
    geography: 'utility + state, not county or address',
    has_address: 'no',
    has_parcel: 'no',
    has_zip: 'no',
    has_county: 'no',
    has_date: 'year',
    has_installer: 'no',
    has_capacity: 'yes-MW',
    residential_focus: 'yes-residential-sector-breakout',
    usable_for_volume: 'state-utility-only',
    notes: 'Cannot size Mecklenburg vs Cabarrus. Service-territory file exists but still not address-level.',
  },
  {
    name: 'NCUC small-generator / CPCN registrations via NCSEA REDB',
    url: 'https://energync.org/map/solar-map/',
    access_method: 'NCSEA map/reports; underlying REDB not a public bulk dump',
    geography: 'NC, county on map; ~40k systems in REDB (all tech, not rooftop-only)',
    has_address: 'unknown-not-public-bulk',
    has_parcel: 'unknown',
    has_zip: 'unknown',
    has_county: 'yes-on-map',
    has_date: 'unknown',
    has_installer: 'unknown',
    has_capacity: 'yes-in-reports',
    residential_focus: 'mixed-rooftop-and-utility-scale',
    usable_for_volume: 'county-totals-if-NCSEA-shares-extract; not DIY-bulk',
    notes: 'NCSEA extracts NCUC registrations. Interactive map, no FeatureServer found. Ask NCSEA for county rooftop counts rather than scraping the map.',
  },
  {
    name: 'LBNL Tracking the Sun public project file',
    url: 'https://emp.lbl.gov/tracking-the-sun',
    access_method: 'annual public CSV (https://bit.ly/trackingthesun2025); no scrape',
    geography: 'US project-level; state and often county; street address usually stripped',
    has_address: 'usually-no-public-file',
    has_parcel: 'no',
    has_zip: 'sometimes',
    has_county: 'often',
    has_date: 'yes-install-year',
    has_installer: 'sometimes',
    has_capacity: 'yes',
    residential_focus: 'yes-distributed-PV',
    usable_for_volume: 'yes-if-NC-county-field-populated',
    notes: 'Download and filter state=NC, customer=residential. Coverage of NC is incomplete vs CA/AZ because LBNL depends on contributing agencies. Large file; not ingested here.',
  },
  {
    name: 'NREL SolarTRACE',
    url: 'https://data.nlr.gov/submissions/160',
    access_method: 'AHJ/utility cycle-time workbook; project-level withheld',
    geography: 'AHJ + utility medians, not properties',
    has_address: 'no',
    has_parcel: 'no',
    has_zip: 'no',
    has_county: 'AHJ-name',
    has_date: 'year-buckets',
    has_installer: 'no',
    has_capacity: 'size-bins',
    residential_focus: 'yes',
    usable_for_volume: 'no-not-a-census',
    notes: 'Installer-contributed sample (~22% of US residential). Confidential project rows. Use only for permitting-time context.',
  },
  {
    name: 'OpenPV / OpenEI',
    url: 'https://openei.org/',
    access_method: 'OpenPV retired; OpenEI has no NC rooftop census',
    geography: 'n/a',
    has_address: 'no',
    has_parcel: 'no',
    has_zip: 'no',
    has_county: 'no',
    has_date: 'no',
    has_installer: 'no',
    has_capacity: 'no',
    residential_focus: 'n/a',
    usable_for_volume: 'no',
    notes: 'OpenPV is not a living successor dataset for NC rooftop addresses.',
  },
  {
    name: 'DOE / Data.gov',
    url: 'https://catalog.data.gov/',
    access_method: 'catalog search',
    geography: 'no NC residential rooftop permit dump found',
    has_address: 'no',
    has_parcel: 'no',
    has_zip: 'no',
    has_county: 'no',
    has_date: 'no',
    has_installer: 'no',
    has_capacity: 'no',
    residential_focus: 'n/a',
    usable_for_volume: 'no-for-this-footprint',
    notes: 'EIA 861 is the relevant federal file. No Charlotte-metro rooftop permit dataset on data.gov.',
  },
  {
    name: 'BLDS / permitdata.org',
    url: 'https://permitdata.org/',
    access_method: 'aggregated building permits; NC coverage sparse',
    geography: 'selected US cities; Charlotte/Meck not a known BLDS bulk feed we can use',
    has_address: 'sometimes',
    has_parcel: 'sometimes',
    has_zip: 'sometimes',
    has_county: 'sometimes',
    has_date: 'yes',
    has_installer: 'sometimes',
    has_capacity: 'no',
    residential_focus: 'mixed',
    usable_for_volume: 'no-for-this-work',
    notes: 'Did not find an official Meck/Cabarrus/Rowan BLDS dump. Commercial aggregators (PermitGrab) scrape portals — out of scope.',
  },
  {
    name: 'Google Project Sunroof Data Explorer',
    url: 'https://sunroof.withgoogle.com/',
    access_method: 'public aggregator of rooftop potential, not a permit registry',
    geography: 'county/city',
    has_address: 'no-bulk',
    has_parcel: 'no',
    has_zip: 'yes-explorer',
    has_county: 'yes',
    has_date: 'no',
    has_installer: 'no',
    has_capacity: 'potential-not-installed',
    residential_focus: 'yes-potential',
    usable_for_volume: 'no-existing-install-count',
    notes: 'Measures viable roofs, not installed systems. Do not use as a completeness check.',
  },
  {
    name: 'Cabarrus CAMA Real Property Permit CSV',
    url: 'https://gis-cabarrus.opendata.arcgis.com/search',
    access_method: 'SharePoint open-data CSV already wired in collectors/cabarrus.ts',
    geography: 'Cabarrus parcels',
    has_address: 'no-on-permit-csv',
    has_parcel: 'yes',
    has_date: 'yes',
    has_zip: 'no',
    has_county: 'yes',
    has_installer: 'no',
    has_capacity: 'no',
    residential_focus: 'mixed-all-permit-types',
    usable_for_volume: 'partial-solar-notes-collapse-after-2019',
    notes: 'Prior audit: ~344 solar-ish notes, no contractor. Complements GIS but does not replace Accela 2019+.',
  },
]
