'use client'

import { useEffect, useMemo, useState } from 'react'
import AgreementDocument from './AgreementDocument'
import { EMPLOYEE_AGREEMENT_TEMPLATES, type EmployeeAgreementKey, type EmployeeAgreementTemplate } from '@/lib/employee-comp-agreements'

type AgreementRow = { id: string; agreement_key: EmployeeAgreementKey; agreement_version: string; status: string; effective_date: string; delivery_error: string | null; send_claimed_at: string | null }
type AgreementDetail = { agreement: { agreement_snapshot: EmployeeAgreementTemplate & { employeeName: string; employeeEmail: string; effectiveDate: string }; agreement_content_hash: string; status: string; manager_signed_name: string; manager_signed_at: string; rep_signed_name: string | null; rep_signed_at: string | null }; events: { event_type: string; actor_name: string | null; created_at: string }[] }
const statusLabel: Record<string, string> = { manager_signed: 'Manager signed - not sent', sending: 'Sending', sent: 'Sent - awaiting rep', rep_signed: 'Fully signed', delivery_failed: 'Delivery failed', declined: 'Declined', voided: 'Voided' }

export default function EmployeeAgreementPanel({ user }: { user: { id: string; full_name: string | null; email: string | null } }) {
  const [rows, setRows] = useState<AgreementRow[]>([]); const [loading, setLoading] = useState(true); const [open, setOpen] = useState(false); const [step, setStep] = useState(1)
  const [agreementKey, setAgreementKey] = useState<EmployeeAgreementKey>('field_marketer')
  const [effectiveDate, setEffectiveDate] = useState(() => { const date = new Date(); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}` })
  const [managerName, setManagerName] = useState(''); const [reviewed, setReviewed] = useState(false); const [consent, setConsent] = useState(false); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState<string | null>(null); const [requestKey, setRequestKey] = useState('')
  const [detail, setDetail] = useState<AgreementDetail | null>(null)
  const template = useMemo(() => EMPLOYEE_AGREEMENT_TEMPLATES[agreementKey], [agreementKey])
  const loadRows = async () => { setLoading(true); const response = await fetch(`/api/admin/employee-agreements?userId=${encodeURIComponent(user.id)}`); if (response.ok) { const data = await response.json(); setRows(data.agreements || []) }; setLoading(false) }
  useEffect(() => { loadRows() }, [user.id])
  const reset = () => { setStep(1); setReviewed(false); setConsent(false); setManagerName(''); setError(null); setRequestKey(''); setOpen(false) }
  const begin = () => { setRequestKey(crypto.randomUUID()); setError(null); setOpen(true) }
  const createAndSend = async () => {
    if (!managerName.trim() || !consent) { setError('Enter your full name and confirm electronic-signature consent.'); return }
    setSubmitting(true); setError(null)
    const response = await fetch('/api/admin/employee-agreements', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ userId: user.id, agreementKey, effectiveDate, managerSignedName: managerName.trim(), consent: true, requestKey }) })
    const data = await response.json(); setSubmitting(false)
    if (!response.ok) { setError(data.error || 'Unable to create and send agreement.'); return }
    reset(); await loadRows()
  }
  const resend = async (agreementId: string) => { setError(null); const response = await fetch('/api/admin/employee-agreements', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ agreementId }) }); if (!response.ok) { const data = await response.json(); setError(data.error || 'Unable to resend agreement.'); return }; await loadRows() }
  const viewRecord = async (agreementId: string) => { setError(null); const response = await fetch(`/api/admin/employee-agreements?userId=${encodeURIComponent(user.id)}&agreementId=${encodeURIComponent(agreementId)}`); if (!response.ok) { setError('Unable to load the agreement record.'); return }; setDetail(await response.json()) }
  const recipientEmail = user.email || ''
  return <div className="rounded-lg border border-green-200 bg-green-50 p-4">
    <div className="flex items-start justify-between gap-3"><div><h3 className="text-sm font-semibold text-gray-900">Compensation agreements</h3><p className="mt-1 text-xs text-gray-600">Manager signs first, then the agreement is emailed automatically to the rep.</p></div><button type="button" onClick={begin} disabled={!user.full_name || !recipientEmail} className="shrink-0 rounded-lg bg-green-700 px-3 py-2 text-xs font-semibold text-white hover:bg-green-800 disabled:opacity-50">Prepare agreement</button></div>
    {error && !open && <p role="alert" className="mt-2 text-xs text-red-700">{error}</p>}
    <div className="mt-3 space-y-2">{loading ? <p className="text-xs text-gray-500">Loading agreements...</p> : rows.length === 0 ? <p className="text-xs text-gray-500">No agreements yet.</p> : rows.map((row) => { const stalled = row.status === 'sending' && row.send_claimed_at && new Date(row.send_claimed_at).getTime() < Date.now() - 5 * 60 * 1000; return <div key={row.id} className="rounded-lg border bg-white p-3 text-xs"><div className="flex justify-between gap-3"><strong>{EMPLOYEE_AGREEMENT_TEMPLATES[row.agreement_key]?.roleName || row.agreement_key}</strong><span>{stalled ? 'Send stalled' : statusLabel[row.status] || row.status}</span></div><p className="mt-1 text-gray-500">Effective {row.effective_date} · Version {row.agreement_version}</p>{row.delivery_error && <p className="mt-1 text-red-700">{row.delivery_error}</p>}<div className="mt-2 flex gap-4"><button type="button" onClick={() => viewRecord(row.id)} className="font-semibold text-green-700 hover:underline">View agreement record</button>{(['manager_signed', 'delivery_failed', 'sent'].includes(row.status) || stalled) && <button type="button" onClick={() => resend(row.id)} className="font-semibold text-green-700 hover:underline">{stalled ? 'Retry stalled send' : row.status === 'manager_signed' ? 'Send agreement' : row.status === 'sent' ? 'Send a new link' : 'Retry send'}</button>}</div></div> })}</div>
    {detail && <div role="dialog" aria-modal="true" aria-labelledby="agreement-record-title" className="fixed inset-0 z-[70] flex items-center justify-center bg-black/60 p-4"><div className="max-h-[92vh] w-full max-w-4xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl"><div className="mb-5 flex items-center justify-between"><h2 id="agreement-record-title" className="text-lg font-bold">Permanent agreement record</h2><button type="button" onClick={() => setDetail(null)} aria-label="Close record" className="rounded p-2 hover:bg-gray-100">✕</button></div><AgreementDocument agreement={detail.agreement.agreement_snapshot} employeeName={detail.agreement.agreement_snapshot.employeeName} effectiveDate={detail.agreement.agreement_snapshot.effectiveDate} /><div className="mt-5 grid gap-3 rounded-lg bg-gray-50 p-4 text-sm sm:grid-cols-2"><p><strong>Manager signature:</strong><br />{detail.agreement.manager_signed_name}<br />{new Date(detail.agreement.manager_signed_at).toLocaleString()}</p><p><strong>Rep signature:</strong><br />{detail.agreement.rep_signed_name || 'Awaiting signature'}{detail.agreement.rep_signed_at && <><br />{new Date(detail.agreement.rep_signed_at).toLocaleString()}</>}</p><p className="break-all sm:col-span-2"><strong>Document fingerprint:</strong><br /><span className="font-mono text-xs">{detail.agreement.agreement_content_hash}</span></p></div><h3 className="mt-5 font-semibold">Audit history</h3><ol className="mt-2 space-y-1 text-sm">{detail.events.map((event, index) => <li key={`${event.created_at}-${index}`}>{new Date(event.created_at).toLocaleString()} — {event.event_type.replaceAll('_', ' ')}{event.actor_name ? ` by ${event.actor_name}` : ''}</li>)}</ol><div className="mt-5 flex justify-end"><button type="button" onClick={() => window.print()} className="rounded-lg border px-4 py-2 font-semibold">Print / save PDF</button></div></div></div>}
    {open && <div role="dialog" aria-modal="true" aria-labelledby="employee-agreement-title" className="fixed inset-0 z-[60] flex items-center justify-center bg-black/60 p-4"><div className="max-h-[92vh] w-full max-w-4xl overflow-y-auto rounded-2xl bg-white shadow-2xl"><div className="sticky top-0 z-10 flex items-center justify-between border-b bg-white px-6 py-4"><div><h2 id="employee-agreement-title" className="text-lg font-bold">Compensation agreement</h2><p className="text-xs text-gray-500">Step {step} of 3 · {user.full_name || recipientEmail}</p></div><button type="button" onClick={reset} className="rounded p-2 text-gray-500 hover:bg-gray-100" aria-label="Close">✕</button></div><div className="p-6">{error && <div role="alert" className="mb-4 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
      {step === 1 && <div className="space-y-5"><div><label className="mb-1 block text-sm font-medium">Plan</label><select value={agreementKey} onChange={(event) => setAgreementKey(event.target.value as EmployeeAgreementKey)} className="w-full rounded-lg border px-3 py-2"><option value="field_marketer">Field Marketer</option><option value="senior_field_marketer">Senior Field Marketer</option><option value="closer">Closer</option></select></div><div><label className="mb-1 block text-sm font-medium">Effective date</label><input type="date" value={effectiveDate} onChange={(event) => setEffectiveDate(event.target.value)} className="w-full rounded-lg border px-3 py-2" required /></div><div className="rounded-lg bg-gray-50 p-4 text-sm"><strong>{template.roleName}</strong><p className="mt-1 text-gray-600">{template.summary}</p></div><div className="flex justify-end"><button type="button" onClick={() => effectiveDate ? setStep(2) : setError('Effective date is required.')} className="rounded-lg bg-green-700 px-4 py-2 font-semibold text-white">Review agreement</button></div></div>}
      {step === 2 && <div><AgreementDocument agreement={template} employeeName={user.full_name || recipientEmail} effectiveDate={effectiveDate} /><label className="mt-4 flex items-start gap-3 text-sm"><input type="checkbox" checked={reviewed} onChange={(event) => setReviewed(event.target.checked)} className="mt-1" /><span>I reviewed the complete agreement and confirmed this is the correct plan for this rep.</span></label><div className="mt-5 flex justify-between"><button type="button" onClick={() => setStep(1)} className="rounded-lg border px-4 py-2">Back</button><button type="button" onClick={() => reviewed ? setStep(3) : setError('Confirm your review before signing.')} className="rounded-lg bg-green-700 px-4 py-2 font-semibold text-white">Continue to signature</button></div></div>}
      {step === 3 && <div className="space-y-5"><div className="rounded-lg border bg-gray-50 p-4"><p className="text-sm font-semibold">Manager electronic signature</p><p className="mt-1 text-xs text-gray-500">The exact agreement above will be locked to version {template.version} and emailed to {recipientEmail}.</p></div><div><label className="mb-1 block text-sm font-medium">Type your full legal name</label><input value={managerName} onChange={(event) => setManagerName(event.target.value)} className="w-full rounded-lg border px-3 py-2 text-lg italic" /></div><label className="flex items-start gap-3 text-sm"><input type="checkbox" checked={consent} onChange={(event) => setConsent(event.target.checked)} className="mt-1" /><span>I intend this typed name to be my electronic signature and authorize the CRM to send this locked agreement to the rep.</span></label><div className="flex justify-between"><button type="button" onClick={() => setStep(2)} className="rounded-lg border px-4 py-2">Back</button><button type="button" onClick={createAndSend} disabled={submitting} className="rounded-lg bg-green-700 px-4 py-2 font-semibold text-white disabled:opacity-50">{submitting ? 'Signing and sending...' : 'Sign and send to rep'}</button></div></div>}
    </div></div></div>}
  </div>
}
